[package]
name = "oblivion-recognition"
version = "0.1.0"
edition = "2024"

[dependencies]
oblivion-common = { path = "../../crates/oblivion-common" }

axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
rdkafka = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
dotenvy = { workspace = true }
rand = { workspace = true }
